In [1]:
import numpy as np
from datetime import date, timedelta

 1. Create a 3x3x3 array with random values

In [2]:
arr = np.random.rand(3,3,3)
arr

array([[[0.3654435 , 0.93676986, 0.40711966],
        [0.46905385, 0.46179796, 0.09737786],
        [0.49018183, 0.23559205, 0.0296402 ]],

       [[0.62183965, 0.12874588, 0.90011037],
        [0.79836314, 0.02222253, 0.05988598],
        [0.24513276, 0.16952072, 0.19562498]],

       [[0.41894234, 0.33377438, 0.12174441],
        [0.6166362 , 0.31764083, 0.87549996],
        [0.40114879, 0.13240787, 0.93965785]]])


2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [5]:
arr = np.diag(np.arange(4) + 1, k = -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])


3. Create a 8x8 matrix and fill it with a checkerboard pattern

In [7]:
arr = np.tile(np.array([[0,1],[1,0]]), (4,4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

4. Normalize a 5x5 random matrix

In [9]:
arr = np.random.random((5,5))
arr = (arr - np.mean (arr)) / (np.std (arr))
arr

array([[-0.22647621,  0.96562366,  1.41014424, -0.25907078, -0.88766831],
       [ 0.64308134,  0.61689822, -1.39811427, -0.18038869, -1.61976796],
       [-1.75369492, -1.36250866, -0.63171475,  1.15643588, -0.82053779],
       [-0.19427369,  1.07147077,  0.43555628,  0.17816173,  0.62515597],
       [-1.62622258,  1.09595825,  0.68267683,  1.31764648,  0.76162897]])

5. How to find common values between two arrays

In [10]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)

np.intersect1d(arr1, arr2)


array([1, 2, 3, 4, 9])


6. How to get the dates of yesterday, today and tomorrow?

In [11]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2020-07-25 2020-07-26 2020-07-27



7. Consider two random array A and B, check if they are equal


In [12]:
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)

equal = np.array_equal(arr1,arr2)
print(f'Array1:\n{arr1}\n\n')
print(f'Array2:\n{arr2}\n\n')
print(f'Equality: {equal}')


Array1:
[[0.83395425 0.93083508 0.38101558]
 [0.19501238 0.73445152 0.63617213]
 [0.80269981 0.83187279 0.41098304]]


Array2:
[[0.6033189  0.30689359 0.44287391]
 [0.60624698 0.61035278 0.25975644]
 [0.09532046 0.256244   0.33984758]]


Equality: False


8. Create random vector of size 10 and replace the maximum value by 0

In [13]:
arr = np.random.rand(10)
arr[arr.argmax()] = 0
arr

array([0.09082751, 0.18553106, 0.7841769 , 0.58361809, 0.        ,
       0.44254667, 0.40181269, 0.79374704, 0.65770025, 0.15415089])

In [14]:
9. How to print all the values of an array?

Object `array` not found.


In [ ]:
9. How to print all the values of an array

In [15]:
arr = np.ones((10, 10))
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]



10. Subtract the mean of each row of a matrix

In [17]:
arr = np.random.rand(3,3)
arr_mean = arr - arr.mean(axis=1, keepdims=True)

arr_mean

array([[ 0.08568977, -0.07805564, -0.00763414],
       [ 0.0162153 , -0.09772411,  0.08150881],
       [ 0.16096263,  0.13686226, -0.29782488]])


11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [19]:
arr1 = np.ones(5)
arr2 = np.random.randint(0, len(arr1), 10)
arr1 += np.bincount(arr2, minlength = len(arr1))
arr1


array([4., 2., 3., 2., 4.])

12. How to get the diagonal of a dot product?

In [20]:
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,3))

np.einsum("ij,ji->i", arr1, arr2)

array([46, 28, 65])

In [21]:
13. How to find the most frequent value in an array?

Object `array` not found.


In [ ]:
13. How to find the most frequent value in an array

In [22]:
arr = np.random.randint(0,10,20)
print(arr)
max(set(arr), key = list(arr).count)

[2 7 6 1 8 5 1 3 2 5 2 4 7 6 6 3 6 5 8 5]


5

14. How to get the n largest values of an array

In [25]:
arr = np.random.randint(0,10,50)
np.bincount(arr).argmax()

2

In [27]:
15. How to create a record array from a regular array?

Object `array` not found.


In [ ]:
15. How to create a record array from a regular array

In [28]:

arr = np.array([("Science", 88.5, 90),
                 ("Maths", 87, 99),
             ("English", 85.5, 91)])

print(arr)
print("\nRECORD ARRAY")
record = np.core.records.fromarrays(arr.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
record


[['Science' '88.5' '90']
 ['Maths' '87' '99']
 ['English' '85.5' '91']]

RECORD ARRAY


rec.array([(b'Science', 88.5, 90), (b'Maths', 87. , 99),
           (b'English', 85.5, 91)],
          dtype=[('col1', 'S80'), ('col2', '<f8'), ('col3', '<i8')])